import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#1B2838',
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    width: '100%',
    height: 65,
    backgroundColor: '#1C1C1C',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 10,
  },
  headerTexto:{
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  card: {
    marginTop: 15,
    width: 300,
    borderRadius: 6,
    backgroundColor: '#2A475E',
    marginRight: 10,
    height: 350,
    marginBottom: 50,
    shadowColor: '#000', // Mantém a sombra branca para testes
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 10,
  },
  imageContainer: {
    width: '100%',
    height: 200,
    backgroundColor: '#000',
  },
  gameImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  infoContainer: {
    padding: 10,
  },
  gameTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  offerTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    marginBottom: 2,
  },
  offerValidity: {
    color: '#FFFFFF',
    fontSize: 12,
    marginBottom: 8,
  },
  discountRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  discountBadge: {
    backgroundColor: '#5C7E10',
    borderRadius: 3,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 10,
  },
  discountText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  priceContainer: {
    flexDirection: 'column',
  },
  oldPrice: {
    color: '#FFFFFF',
    textDecorationLine: 'line-through',
    fontSize: 14,
    marginBottom: 2,
  },
  newPrice: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  textoDestaques:{
    color: '#fff',
    alignSelf: 'flex-start',
    fontSize: 15,
    fontWeight: '500',
  },
  textoOfertas:{
    marginTop: 50,
    color: '#fff',
    alignSelf: 'flex-start',
    fontSize: 15,
    fontWeight: '500',
  },
    tituloExplorar:{
    color: '#fff',
    alignSelf: 'flex-start',
    fontSize: 15,
    fontWeight: '500',
  },
  botaoExplorar:{
    backgroundColor: '#4bf',
    height: 65,
    width: '49%',
    marginVertical: 7,
    marginRight: 5,
    alignItems: 'center',
    borderRadius: 3.5,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 10,
  },
  viewAlinhar:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  botaoCategoria:{
    height: 250,
    width: 250,
    marginVertical: 7,
    marginRight: 10,
    alignItems: 'center',
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 10,
  },
    gradiente: {
      height: '100%',
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 5,
  },
  textoCategoria:{
    backgroundColor:'#fff',
    height: 45,
    width: '50%',
    textAlign: 'center',
    borderRadius: 4,
    marginTop: 100,
    fontSize: 30,
  },
  imagemCategoria:{
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    borderRadius: 5,
  },
  textoExplorar:{
    fontWeight: 'bold',
    fontSize: 21.5,
    color: '#fff',
  },
  gradiente2: {
    borderRadius: 5,
    height: 150,
  },
  viewPesquisa:{
    height: 175,
    width: '100%',
    marginBottom: 50,
  },
  barraPesquisa:{
    fontSize: 18,
    marginVertical: 10,
    marginHorizontal: 10,
    paddingVertical: 5,
    paddingHorizontal: 10,
    flex: 1, // 90% da largura da tela
    borderRadius: 5,
    backgroundColor: '#50849B',
    borderWidth: 1,
    borderColor: '#aaa',
    outlineColor: '#05f',
  },
  viewPesquisa2:{
    flexDirection: 'row',
    position: 'relative',
  },
  viewPesquisa3:{
    flexDirection: 'row',
  },
    btn: {
    width: 50,
    alignSelf: 'center',
    height: 34,
    borderRadius: 5,
    backgroundColor: '#3BAED6',
    position: 'absolute',
    right: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
    gradiente3: {
    height: 175,
    width: '100%',
    marginBottom: 50,
  },
  textoPesquisa:{
    marginVertical: 10,
    marginHorizontal: 20,
    color: '#fff',
    fontWeight: 'bold',
  },
  imgPerfil:{
    width: 22,
    height: 22,
    resizeMode: 'cover',
    marginLeft: 15,
    marginTop: 8,
  },
    textoPesquisa2:{
    marginVertical: 10,
    marginLeft: 13,
    color: '#fff',
    fontWeight: 'bold',
  },
});

export default styles;